Make nullable parameters explicity nullable for PHP 8.4
reactphp/child-process pull request #111
Opened 2024-12-04 04:59 UTC by emteknetnz

Implicitly nullable parameter types are deprecated in PHP 8.4

https://www.php.net/manual/it/migration84.deprecated.php#migration84.deprecated.core.implicitly-nullable-parameter

2024-12-19 16:19 UTC, WyriHaximus requested changes
Hey, thanks for taking the time to address this. Did find something that requires updating due to the PHP versions in range

2024-12-19 16:19 UTC, WyriHaximus commented on src/Process.php
> +    public function start(?LoopInterface $loop = null, $interval = 0.1)
Could you update this method the same way this method has been updated in another package? https://github.com/reactphp/socket/pull/318/files#diff-2c0b16424077d1ecafdbbca23aa3f137bc007241b00fe55dd536434c147326ca This way we can ensure it runs on all PHP versions in rage

2024-12-24 12:40 UTC, clue requested changes
@emteknetnz Thanks for looking into this. I've just replied with a status update in #110 and plan to get this in for the next release.

Unfortunately this requires a bit more work to support legacy PHP versions as suggested in #108. The good news is, we've already prepared all the required changes there and only need to backport this as discussed in #110.

Once #113 is merged, we can move forward with this. In the meantime, I don't think there's much that needs to be done here. I'll get back this once we make progress.

2024-12-31 22:49 UTC, WyriHaximus commented
Closing this PR as it has been resolved through #114

2024-12-31 22:49 UTC, closed without merging